version: "3.9"
services:
  bomber-zookeeper:
    container_name: bomber-zookeeper
    image: zookeeper:3.7.0
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  bomber-example-accounts-app:
    build:
      context: ./bomber-example/bomber-accounts-users-app
      dockerfile: Dockerfile
    container_name: bomber-example-users
    image: bomber/bomber-accounts-users-app
    ports:
      - "8083:8083"

  bomber-example-users-app:
    build:
      context: ./bomber-example/bomber-example-users-app
      dockerfile: Dockerfile
    container_name: bomber-example-users
    depends_on:
      - bomber-example-accounts-app    
    image: bomber/bomber-example-users-app
    ports:
      - "8082:8082"
    environment:
      EXAMPLE_ACCOUNTS_APP_URL: "bomber-example-accounts:8083"

  bomber-example-app:
    build:
      context: ./bomber-example/bomber-example-app
      dockerfile: Dockerfile
    container_name: bomber-example
    depends_on:
      - bomber-example-accounts-app
      - bomber-example-users-app
    image: bomber/bomber-example-app
    ports:
      - "8081:8081"
    environment:
      EXAMPLE_ACCOUNTS_APP_URL: "bomber-example-accounts:8083"
      EXAMPLE_USERS_APP_URL: "bomber-example-users:8082"

  bomber-atc-app:
    build:
      context: ./bomber-atc-app
      dockerfile: Dockerfile
    container_name: bomber-atc
    depends_on:
      - bomber-zookeeper
    image: bomber/bomber-atc-app:latest
    ports:
      - "8088:8088"
    environment:
      ZOOKEEPER_URL: "bomber-zookeeper:2181"

#  bomber-atc-frontend:
#    build:
#      context: ./bomber-atc-frontend
#      dockerfile: Dockerfile
#    container_name: bomber-frontend
#    image: bomber/bomber-atc-app:latest
#    ports:
#      - "8080:80"

  bomber-carrier-app-9001:
    build:
      context: ./bomber-example/bomber-example-carrier-app
      dockerfile: Dockerfile
    container_name: bomber-carrier-9001
    depends_on:
      - bomber-zookeeper
      - bomber-atc-app
      - bomber-example-gateway-app
    image: bomber/bomber-example-carrier-app
    ports:
      - "9001:9000"
    environment:
      ZOOKEEPER_URL: "bomber-zookeeper:2181"
      EXAMPLE_APP_URL: "bomber-example:8081"

  bomber-carrier-app-9002:
    build:
      context: ./bomber-example/bomber-example-carrier-app
      dockerfile: Dockerfile
    container_name: bomber-carrier-9002
    depends_on:
      - bomber-zookeeper
      - bomber-atc-app 
      - bomber-example-gateway-app
    image: bomber/bomber-example-carrier-app
    ports:
      - "9002:9000"
    environment:
      ZOOKEEPER_URL: "bomber-zookeeper:2181"
      EXAMPLE_APP_URL: "bomber-example:8081"