server:
  port: 8088

spring:
  application:
    name: bomber-atc

  cloud:
    zookeeper:
      connect-string: ${ZOOKEEPER_URL:localhost:2181}
      dependencies:
        bomber-carrier:
          required: false

      dependency:
        ribbon:
          enabled: false
        resttemplate:
          enabled: false

    loadbalancer:
      ribbon:
        enabled: false


  rsocket:
    server:
      port: 8090

atc:
  security:
    username: admin
    password: admin
