server:
  port: 9000

spring:
  application:
    name: bomber-carrier

  cloud:
    zookeeper:
      connect-string: localhost:2181


bomber:
  target:
    url: http://localhost:8080
  squadron:
    members: 1

---
spring:
  profiles: bomber-9001

server:
  port: 9001

---
spring:
  profiles: bomber-9002

server:
  port: 9002
