server:
  port: 9000

spring:
  application:
    name: bomber-carrier

  cloud:
    zookeeper:
      connect-string: ${ZOOKEEPER_URL:localhost:2181}


bomber:
  target:
    url: ${EXAMPLE_APP_URL:http://localhost:8081}
  squadron:
    members: 1

---
spring:
  profiles: bomber-9001

server:
  port: 9001

---
spring:
  profiles: bomber-9002

server:
  port: 9002
